# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lattice < Formula
  desc "Lattice edge agent — secure peer-to-peer networking"
  homepage "https://github.com/alatticeio/lattice"
  version "0.1.0-alpha"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_darwin_amd64.tar.gz"
    sha256 "439b1a815c1a483a7c7ed753881f8b888aa0e966d64093527322f23d30603fdb"

    define_method(:install) do
      bin.install "lattice"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lattice
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "9cf948689c5297a0149dc35e8a2aa11016a7d113d31ab72257fa6f6bc749d4b0"
      define_method(:install) do
        bin.install "lattice"
      end
    end
  end

  test do
    system "#{bin}/lattice", "version"
  end
end
