# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LatticePro < Formula
  desc "Lattice Pro edge agent — secure peer-to-peer networking with Pro features"
  homepage "https://github.com/alatticeio/lattice"
  version "0.1.0-alpha"
  license "Apache 2.0"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice-pro_0.1.0-alpha_linux_amd64.tar.gz"
    sha256 "587d5a72f860f32e9be90ca1aa87ddd1bb80870c0c1e4d5a584209abc8331e6b"
    define_method(:install) do
      bin.install "lattice-pro"
    end
  end

  test do
    system "#{bin}/lattice-pro", "version"
  end
end
