# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lattice < Formula
  desc "Lattice edge agent — secure peer-to-peer networking"
  homepage "https://github.com/alatticeio/lattice"
  version "0.1.0-alpha"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_darwin_amd64.tar.gz"
      sha256 "92de86944dfd8c6a84c88d68f115c1b251590b21c9a5c87253fe81487f9f4ba8"

      define_method(:install) do
        bin.install "lattice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_darwin_arm64.tar.gz"
      sha256 "1857d722cb751aac1567bac9a9fb8551e6d5c341f858be7e8cbac26f39a74699"

      define_method(:install) do
        bin.install "lattice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "c84acd843c466dd5977fae230d328f90a321c09f82b9de1ae4bec9b20918db5a"
      define_method(:install) do
        bin.install "lattice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_linux_arm64.tar.gz"
      sha256 "c4c2be0921a998a50535d3acc9cc7b089a98d30685f1b2b4b1385b7da2ea4f2a"
      define_method(:install) do
        bin.install "lattice"
      end
    end
  end

  test do
    system "#{bin}/lattice", "version"
  end
end
