# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lattice < Formula
  desc "Lattice edge agent — secure peer-to-peer networking"
  homepage "https://github.com/alatticeio/lattice"
  version "0.1.0-alpha"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_darwin_amd64.tar.gz"
      sha256 "aa44790a6fb65528e94a6abaad17f9f414afe62ae95af81a4e508c9b848800d5"

      define_method(:install) do
        bin.install "lattice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_darwin_arm64.tar.gz"
      sha256 "296c64574004fff5ea3fcd5311f613ce5153f4aed9ba047ccdbd8cc54a307658"

      define_method(:install) do
        bin.install "lattice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "5ff2b7c0cce68886aab06cf14d59387917386d7c442024ce2e7a7b7949ce5c06"
      define_method(:install) do
        bin.install "lattice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alatticeio/lattice/releases/download/v0.1.0-alpha/lattice_0.1.0-alpha_linux_arm64.tar.gz"
      sha256 "9864f7bd57331db9365f9e6bae489926f178357e95c1287e42023682c0d4183b"
      define_method(:install) do
        bin.install "lattice"
      end
    end
  end

  test do
    system "#{bin}/lattice", "version"
  end
end
